# Generated by Django 2.0.1 on 2018-04-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='host_to_remote_user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='login_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
    ]
