# Generated by Django 2.0.4 on 2018-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_task_tasklogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'initialize'), (1, 'success'), (2, 'failed'), (3, 'timeout')], default=0),
        ),
    ]
