# Generated by Django 2.0.4 on 2018-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_tasklogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('cmd', '批量任务'), ('file-transfer', '文件传输')], max_length=64),
        ),
    ]
