# Generated by Django 2.0.4 on 2018-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180505_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogdetail',
            name='status',
            field=models.SmallIntegerField(choices=[('0', 'initialized'), ('1', 'success'), ('2', 'failed'), ('3', 'timeout')]),
        ),
    ]
